# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52bee8a65f89fc5798333a96452b7cc785f8d081b9939a0bd6e7b4982ff485b73b26580ea9befab79e1609281731e078332138a9546a2fbd0f88291681329cf2

test:
  secret_key_base: 6b50080381381e1c096746e3d13b9c0f98b0cc0fac9b556b9a5e03dfa77f74e6ab5b94d652265f084baa241d0ff79ced04cad0f98444bbe22e1e8af52599711b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
