class CreateBairros < ActiveRecord::Migration
  def self.up
    create_table :bairros do |t|
      t.string :bairro
      t.string :subprefeitura

      t.timestamps
    end
Bairro.create(:bairro => "Aricanduva", :subprefeitura => "Aricanduva")
Bairro.create(:bairro => "Carrão", :subprefeitura => "Aricanduva")
Bairro.create(:bairro => "Vila Formosa", :subprefeitura => "Aricanduva")
Bairro.create(:bairro => "Butantã", :subprefeitura => "Butantã")
Bairro.create(:bairro => "Morumbi", :subprefeitura => "Butantã")
Bairro.create(:bairro => "Raposo Tavares", :subprefeitura => "Butantã")
Bairro.create(:bairro => "Rio Pequeno", :subprefeitura => "Butantã")
Bairro.create(:bairro => "Vila Sônia", :subprefeitura => "Butantã")
Bairro.create(:bairro => "Campo Limpo", :subprefeitura => "Campo Limpo")
Bairro.create(:bairro => "Capão Redondo", :subprefeitura => "Campo Limpo")
Bairro.create(:bairro => "Vila Andrade", :subprefeitura => "Campo Limpo")
Bairro.create(:bairro => "Cidade Dutra", :subprefeitura => "Capela do Socorro") 
Bairro.create(:bairro => "Grajaú", :subprefeitura => "Capela do Socorro")
Bairro.create(:bairro => "Socorro", :subprefeitura => "Capela do Socorro")
Bairro.create(:bairro => "Cachoeirinha", :subprefeitura => "Casa Verde")
Bairro.create(:bairro => "Casa Verde", :subprefeitura => "Casa Verde") 
Bairro.create(:bairro => "Limão", :subprefeitura => "Casa Verde")
Bairro.create(:bairro => "Cidade Ademar", :subprefeitura => "Cidade Ademar")
Bairro.create(:bairro => "Pedreira", :subprefeitura => "Cidade Ademar")
Bairro.create(:bairro => "Cidade Tiradentes", :subprefeitura => "Cidade Tiradentes")
Bairro.create(:bairro => "Ermelino Matarazzo", :subprefeitura => "Ermelino Matarazzo")
Bairro.create(:bairro => "Ponte Rasa", :subprefeitura => "Ermelino Matarazzo")
Bairro.create(:bairro => "Brasilandia", :subprefeitura => "Freguesia do Ó") 
Bairro.create(:bairro => "Freguesia do Ó", :subprefeitura => "Freguesia do Ó")
Bairro.create(:bairro => "Lajeado", :subprefeitura => "Guaianases")
Bairro.create(:bairro => "Guaianases", :subprefeitura => "Guaianases")
Bairro.create(:bairro => "Cursino", :subprefeitura => "Ipiranga")
Bairro.create(:bairro => "Ipiranga", :subprefeitura => "Ipiranga")
Bairro.create(:bairro => "Sacomã", :subprefeitura => "Ipiranga")
Bairro.create(:bairro => "Itaim Paulista", :subprefeitura => "Itaim Paulista")
Bairro.create(:bairro => "Vila Curuçá", :subprefeitura => "Itaim Paulista") 
Bairro.create(:bairro => "Cidade Líder", :subprefeitura => "Itaquera")
Bairro.create(:bairro => "Itaquera", :subprefeitura => "Itaquera")
Bairro.create(:bairro => "José Bonifácio", :subprefeitura => "Itaquera")
Bairro.create(:bairro => "Parque do Carmo", :subprefeitura => "Itaquera")
Bairro.create(:bairro => "Jabaquara", :subprefeitura => "Jabaquara")
Bairro.create(:bairro => "Jaçanã", :subprefeitura => "Jaçanã")
Bairro.create(:bairro => "Tremembé", :subprefeitura => "Jaçanã")
Bairro.create(:bairro => "Barra Funda", :subprefeitura => "Lapa")
Bairro.create(:bairro => "Jaguara", :subprefeitura => "Lapa")
Bairro.create(:bairro => "Jaguaré", :subprefeitura => "Lapa")
Bairro.create(:bairro => "Perdizes", :subprefeitura => "Lapa")
Bairro.create(:bairro => "Vila Leopoldina", :subprefeitura => "Lapa")
Bairro.create(:bairro => "Jardim Angela", :subprefeitura => "Mboi Mirim")
Bairro.create(:bairro => "Jardim São Luis", :subprefeitura => "Mboi Mirim")
Bairro.create(:bairro => "Agua Rasa", :subprefeitura => "Mooca")
Bairro.create(:bairro => "Belém", :subprefeitura => "Mooca")
Bairro.create(:bairro => "Brás", :subprefeitura => "Mooca") 
Bairro.create(:bairro => "Pari", :subprefeitura => "Mooca")
Bairro.create(:bairro => "Tatuapé", :subprefeitura => "Mooca")
Bairro.create(:bairro => "Marsilac", :subprefeitura => "Parelheiros")
Bairro.create(:bairro => "Parelheiros", :subprefeitura => "Marsilac")
Bairro.create(:bairro => "Artur Alvim", :subprefeitura => "Penha")
Bairro.create(:bairro => "Cangaíba", :subprefeitura => "Penha")
Bairro.create(:bairro => "Penha", :subprefeitura => "Penha")
Bairro.create(:bairro => "Vila Matilde", :subprefeitura => "Penha")
Bairro.create(:bairro => "Anhanguera", :subprefeitura => "Perus")   
Bairro.create(:bairro => "Perus", :subprefeitura => "Perus")
Bairro.create(:bairro => "Alto de Pinheiros", :subprefeitura => "Pinheiros")
Bairro.create(:bairro => "Itaim Bibi", :subprefeitura => "Pinheiros")
Bairro.create(:bairro => "Jardim Paulista", :subprefeitura => "Pinheiros") 
Bairro.create(:bairro => "Pinheiros", :subprefeitura => "Pinheiros")
Bairro.create(:bairro => "Jaragua", :subprefeitura => "Pirituba")
Bairro.create(:bairro => "Pirituba", :subprefeitura => "Pirituba")
Bairro.create(:bairro => "São Domingos", :subprefeitura => "Pirituba")
Bairro.create(:bairro => "Mandaqui", :subprefeitura => "Santana")
Bairro.create(:bairro => "Santana", :subprefeitura => "Santana")
Bairro.create(:bairro => "Tucuruvi", :subprefeitura => "Santana")
Bairro.create(:bairro => "Campo Belo", :subprefeitura => "Santo Amaro")
Bairro.create(:bairro => "Campo Grande", :subprefeitura => "Santo Amaro")
Bairro.create(:bairro => "Santo Amaro", :subprefeitura => "Santo Amaro")
Bairro.create(:bairro => "Iguatemi", :subprefeitura => "São Mateus")
Bairro.create(:bairro => "São Rafael", :subprefeitura => "São Mateus")
Bairro.create(:bairro => "São Mateus", :subprefeitura => "São Mateus") 
Bairro.create(:bairro => "São Miguel", :subprefeitura => "São Miguel")
Bairro.create(:bairro => "Jardim Helena", :subprefeitura => "São Miguel")
Bairro.create(:bairro => "Vila Jacuí", :subprefeitura => "São Miguel")
Bairro.create(:bairro => "Sapopemba", :subprefeitura => "Sapopemba") 
Bairro.create(:bairro => "Bela Vista", :subprefeitura => "Sé")
Bairro.create(:bairro => "Bom Retiro", :subprefeitura => "Sé")
Bairro.create(:bairro => "Cambuci", :subprefeitura => "Sé")
Bairro.create(:bairro => "Consolação", :subprefeitura => "Sé")
Bairro.create(:bairro => "Liberdade", :subprefeitura => "Sé")
Bairro.create(:bairro => "República", :subprefeitura => "Sé") 
Bairro.create(:bairro => "Santa Cecília", :subprefeitura => "Sé") 
Bairro.create(:bairro => "Sé", :subprefeitura => "Sé")
Bairro.create(:bairro => "Vila Guilherme", :subprefeitura => "Vila Guilherme")
Bairro.create(:bairro => "Vila Maria", :subprefeitura => "Vila Guilherme")
Bairro.create(:bairro => "Vila Medeiros", :subprefeitura => "Vila Guilherme")
Bairro.create(:bairro => "Moema", :subprefeitura => "Vila Mariana")
Bairro.create(:bairro => "Saúde", :subprefeitura => "Vila Mariana")
Bairro.create(:bairro => "Vila Mariana", :subprefeitura => "Vila Mariana") 
Bairro.create(:bairro => "São Lucas", :subprefeitura => "Vila Prudente")
Bairro.create(:bairro => "Vila Prudente", :subprefeitura => "Vila Prudente")

  end
end
